#server:
#  port: 8080

#config
spring:
  mvc:
    view:
      prefix: WEB-INF/views/
      suffix: .jsp
  datasource:
#    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:./data/test;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_UPPER=false
#    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:h2:file:./data/test;MODE=MYSQL;DATABASE_TO_UPPER=false
    url: jdbc:h2:file:./data/test;MODE=MYSQL;FILE_LOCK=NO
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    defer-datasource-initialization: true
#    defer-datasource-initialization: false
    hibernate:
      # mode - create, update, none, create-drop, validate
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
  sql:
    init:
#      mode: always
      username: sa
      password:
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql