#server:
#  port: 8080

#config
spring:
  mvc:
    view:
      prefix: WEB-INF/views
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
