-- schema.sql
CREATE TABLE IF NOT EXISTS member (
    member_no INTEGER GENERATED BY DEFAULT AS IDENTITY,
    member_id VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nick_name VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    gender VARCHAR(1) NOT NULL,
    reg_dt DATETIME,
    mod_dt DATETIME,
    PRIMARY KEY (member_no)
);