name: CI/CD for Planify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Java 및 Gradle 설치
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'

    # Gradle Build
    - name: Add execute permissions to gradlew
      run: chmod +x Planify/gradlew

    - name: Build WAR with Gradle
      working-directory: Planify
      run: ./gradlew clean build

    # Docker image Build
    - name: Build Docker image
      working-directory: Planify
      run: docker build -t "${{ secrets.DOCKER_USERNAME }}/planify:latest" .

    # Push Docker image to Docker Hub
    - name: Push Docker image
      run: docker push "${{ secrets.DOCKER_USERNAME }}/planify:latest"

    # Set permissions for SSH private key
    - name: Set permissions for SSH private key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > dev.pem
        chmod 600 dev.pem

    # Deploy Docker container on server
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -i dev.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker pull ${{ secrets.DOCKER_USERNAME }}/planify:latest
        docker stop planify || true
        docker rm planify || true
        docker run -d --name planify -p 9350:8080 ${{ secrets.DOCKER_USERNAME }}/planify:latest
        EOF
