name: CI/CD for Planify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # Java 및 Gradle 설치
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'

    # Gradle Build
    - name: Build WAR with Gradle
      run: ./gradlew clean build

    # Docker image Build
    - name: Build Docker image from Dockerfile
      run: docker build -t planify:latest .

    # remote server to Docker image
    - name: Save Docker image to archive
      run: docker save planify:latest | gzip > planify.tar.gz

    - name: Copy Docker image to server
      uses: appleboy/scp-action@v0.2.1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "planify.tar.gz"
        target: "~/planify.tar.gz"

    # 6. remote server Docker run
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        docker load < ~/planify.tar.gz
        docker stop planify || true
        docker rm planify || true
        docker run -d --name planify -p 9350:8080 planify:latest
        EOF
